name: Tests

on:
  push:
    branches:
      - main

  pull_request:


jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    name: Tests

    steps:


      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache khmercut
        id: khmercut-cache
        uses: actions/cache@v3
        with:
            path: /usr/local/bin/khmercut
            key: khmercut-0.2.0
      - name: Download khmercut if not cached
        if: steps.khmercut-cache.outputs.cache-hit != 'true'
        run: wget https://github.com/semsphy/khmercut-rs/releases/download/0.2.1/khmercut-Linux-x86_64-musl.tar.gz -O /tmp/khmercut.tar.gz

      - name: Extract khmercut if not cached
        if: steps.khmercut-cache.outputs.cache-hit != 'true'
        run: tar -xzf /tmp/khmercut.tar.gz -C /usr/local/bin

      - name: Verify installation
        run: /usr/local/bin/khmercut --version

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-composer-${{ hashFiles('composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: xdebug


      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --ansi

      - name: Tests
        run: composer test
